server:
  port: 8083

aws:
  region: us-east-2
  dynamodb:
    pins-table: Pins
    user-bookmarks-table: UserBookmarks


google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY:}

logging:
  level:
    com.pindrop: DEBUG
